name: Easycommands
"id": 121185,
version: ${project.version}
main: me.clearedspore.easycommands
api-version: '1.21'
commands:
  clear:
    description: Clear your inventory!
    permission: easycommands.clear
    aliases:
      - ci
      - clearinv
      - clearinventory
  gmc:
    description: Change your gamemode to Creative!
    permission: easycommands.gamemode.creative
  gmsp:
    description: Change your gamemode to Spectator!
    permission: easycommands.gamemode.spectator
  gma:
    description: Change your gamemode to Adventure!
    permission: easycommands.gamemode.adventure
  gms:
    description: Change your gamemode to Survival!
    permission: easycommands.gamemode.survival
  feed:
    description: Feed yourself!
    permission: easycommands.feed
  god:
    description: Put yourself in godmode!
    permission: easycommands.god
  repair:
    description: Repair the item in your hand!
    permission: easycommands.repair
  heal:
    description: Heal yourself!
    permission: easycommands.heal
  repairall:
    description: Repair all the items in your inventory!
    permission: easycommands.repairall
    aliases:
      - rpall
  teleport:
    description: Teleport to players or to yourself!
    permission: easycommands.teleport
    aliases:
      - tp
  teleportall:
    description: Teleport all players to you!
    permission: easycommands.teleport.all
    aliases:
      - tpall
  setspawn:
    description: Set the spawnpoint!
    permission: easycommands.setspawn
  spawn:
    description: Go to the spawnpoint!
    permission: easycommands.spawn
  enderchest:
    description: Open your enderchest!
    permission: easycommands.enderchest
    aliases:
      - ec
      - openec
      - openenderchest
      - endersee
  nick:
    description: Nick yourself!
    permission: easycommands.nick
  unnick:
    description: unnick yourself!
    permission: easycommands.nick
  tphere:
    description: Teleport players to you!
    permission: easycommands.teleport.here
  clearchat:
    description: Clear the chat!
    permission: easycommands.clearchat
    aliases:
      - clc
  back:
    description: Go back to your latest death location
    permission: easycommands.back
  freeze:
    description: Freeze a player
    permission: easycommands.freeze
  invsee:
    description: Open a player's inventory
    permission: easycommands.inventorysee
  easycommands:
    description: get some info about the plugin or reload it!
    permission: easycommands.easycommands
  kill:
    description: kill yourself/other players
    permission: easycommands.kill
  copyinventory:
    description: copy a player's inventory and give it to yourself
    permission: easycommands.copyinventory
    aliases:
      - copyinv
  setwarp:
    description: set a new warp!
    usage: /setwarp <name>
    permission: easycommands.warp.setwarp
  warp:
    description: teleport to a warp!
    usage: /warp <name>
    permission: easycommands.warp.warp
  delwarp:
    description: delete a warp!
    usage: /delwarp <name>
    permission: easycommands.warp.delwarp
  delwarpall:
    description: delete all the warps. THIS CAN ONLY BE DONE TROUGH CONSOLE!
    usage: /delwarpall
    permission: easycommands.warp.delwarpall
  getlogs:
    description: Get the logs off a player
    usage: /getlogs <player>
    permission: easycommands.getlogs
  kick:
    description: Kick someone
    permission: easycommands.kick
    usage: /kick <player>
  maintenance:
    description: Maintenance function!
    permission: easycommands.maintenance
    usage: /maintenance <arguments>
permissions:
  easycommands.warp.warp.*:
    description: Access to all warps!
    default: false
  easycommands.update:
    description: get a notification when there is a new update!
    default: false
  easycommands.logs.admin:
    description: Logs for admins
    default: false
  easycommands.staff:
    description: General permissions for staff
    default: false
  easycommands.freeze.cmdblock:
    description: Bypass the cmd block
    default: false
  easycommands.maintenance.toggle:
    description: Turn the maintenance on/off
    default: false
  easycommands.maintenance.add:
    description: Add a player to the maintenance whitelist
    default: false
  easycommands.maintenance.remove:
    description: Remove a player from the maintenance whitelist
    default: false
  easycommands.maintenance.kickall:
    description: Kick all the players that are not on the maintenance whitelist
    default: false
  easycommands.maintenance.*:
    description: Permission to all maintenance commands
    default: false

