name: Easycommands
"id": 121185,
version: 1.8
main: me.clearedspore.easycommands
api-version: '1.21'
commands:
  clear:
    description: Clear your inventory!
    permission: easycommands.clear
    aliases:
      - ci
      - clearinv
      - clearinventory
  gmc:
    description: Change your gamemode to Creative!
    permission: easycommands.gamemode.creative
  gmsp:
    description: Change your gamemode to Spectator!
    permission: easycommands.gamemode.spectator
  gma:
    description: Change your gamemode to Adventure!
    permission: easycommands.gamemode.adventure
  gms:
    description: Change your gamemode to Survival!
    permission: easycommands.gamemode.survival
  gamemode:
    description: Change your gamemode!
    permission: easycommands.gamemode
    aliases:
      - gm
  feed:
    description: Feed yourself!
    permission: easycommands.feed
  god:
    description: Put yourself in godmode!
    permission: easycommands.god
  repair:
    description: Repair the item in your hand!
    permission: easycommands.repair
  heal:
    description: Heal yourself!
    permission: easycommands.heal
  repairall:
    description: Repair all the items in your inventory!
    permission: easycommands.repairall
    aliases:
      - rpall
  teleport:
    description: Teleport to players or to yourself!
    permission: easycommands.teleport
    aliases:
      - tp
  teleportall:
    description: Teleport all players to you!
    permission: easycommands.teleport.all
    aliases:
      - tpall
  setspawn:
    description: Set the spawnpoint!
    permission: easycommands.setspawn
  spawn:
    description: Go to the spawnpoint!
    permission: easycommands.spawn
  enderchest:
    description: Open your enderchest!
    permission: easycommands.enderchest
    aliases:
      - ec
      - openec
      - openenderchest
      - endersee
  nick:
    description: Nick yourself!
    permission: easycommands.nick
  unnick:
    description: unnick yourself!
    permission: easycommands.nick
  tphere:
    description: Teleport players to you!
    permission: easycommands.teleport.here
  tpa:
    description: request a teleport
    permission: easycommands.teleport.tpa
  tpahere:
    description: request a teleport here
    permission: easycommands.teleport.tpahere
  tpaccept:
    description: Accept a teleport request
    permission: easycommands.teleport.accept
  clearchat:
    description: Clear the chat!
    permission: easycommands.clearchat
    aliases:
      - clc
  back:
    description: Go back to your latest death location
    permission: easycommands.back
  freeze:
    description: Freeze a player
    permission: easycommands.freeze
  invsee:
    description: Open a player's inventory
    permission: easycommands.inventorysee
  easycommands:
    description: get some info about the plugin or reload it!
    permission: easycommands.easycommands
  kill:
    description: kill yourself/other players
    permission: easycommands.kill
  copyinventory:
    description: copy a player's inventory and give it to yourself
    permission: easycommands.copyinventory
    aliases:
      - copyinv
  setwarp:
    description: set a new warp!
    usage: /setwarp <name>
    permission: easycommands.warp.setwarp
  warp:
    description: teleport to a warp!
    usage: /warp <name>
    permission: easycommands.warp.warp
  delwarp:
    description: delete a warp!
    usage: /delwarp <name>
    permission: easycommands.warp.delwarp
  delwarpall:
    description: delete all the warps. THIS CAN ONLY BE DONE TROUGH CONSOLE!
    usage: /delwarpall
    permission: easycommands.warp.delwarpall
  getlogs:
    description: Get the logs off a player
    usage: /getlogs <player>
    permission: easycommands.getlogs
  kick:
    description: Kick someone
    permission: easycommands.kick
    usage: /kick <player>
  maintenance:
    description: Maintenance function!
    permission: easycommands.maintenance
    usage: /maintenance <arguments>
  chatcolor:
    description: Chatcolor GUI!
    permission: easycommands.chatcolor
  item:
    description: Edit the item in your hand!
    permission: easycommands.item
  msg:
    description: Send a private message to someone!
    permission: easycommands.msg
    aliases:
      - whisper
      - message
      - pm
      - privatemsg
      - privatemessage
  pickup:
    description: Settings for pickups
    permission: easycommands.pickup
  sudo:
    description: Let a player run a command as another player!
    permission: easycommands.sudo
  settings:
    description: Open the settings gui!
    permission: easycommands.settings
    aliases:
      - options
      - preferences
  flight:
    description: Toggle your flight
    permission: easycommands.flight
    aliases:
      - fly
      - togglefly
  workbench:
    description: Open the workbench gui
    permission: easycommands.workbench
    aliases:
      - craft
      - craftingtable
  anvil:
    description: open the anvil gui
    permission: easycommands.anvil
  loom:
    description: open the loom gui
    permission: easycommands.loom
  cartography:
    description: open the cartography gui
    permission: easycommands.cartography
  furnace:
    description: open the furnace gui
    permission: easycommands.furnace
  smithingtable:
    description: open the smithingtable gui
    permission: easycommands.smithingtable
  report:
    description: report a player!
    permission: easycommands.report.report
  reports:
    description: get the reports
    permission: easycommands.reports.getreports
    aliases:
      - getreports
      - viewreports
      - openreportsgui
  staffhelp:
    description: Request help!
    permission: easycommands.staffhelp
    aliases:
      - shelp
      - helpstaff
      - requesthelp
  dynamiccommand:
    description: Placeholder for dynamically registered commands
  broadcast:
    description: Broadcast a message to all online players!
    permission: easycommands.broadcast
    aliases:
      - bc
      - bcast
      - broadcastmessage
permissions:
  easycommands.warp.warp.*:
    description: Access to all warps!
    default: op
  easycommands.update:
    description: get a notification when there is a new update!
    default: op
  easycommands.logs.admin:
    description: Logs for admins
    default: op
  easycommands.staff:
    description: General permissions for staff
    default: op
  easycommands.freeze.cmdblock:
    description: Bypass the cmd block
    default: op
  easycommands.maintenance.toggle:
    description: Turn the maintenance on/off
    default: op
  easycommands.maintenance.add:
    description: Add a player to the maintenance whitelist
    default: op
  easycommands.maintenance.remove:
    description: Remove a player from the maintenance whitelist
    default: op
  easycommands.maintenance.kickall:
    description: Kick all the players that are not on the maintenance whitelist
    default: op
  easycommands.maintenance.*:
    description: Permission to all maintenance commands
    default: op
  easycommands.chatcolor.red:
    description: Allows the player to use red chat color.
    default: op
  easycommands.chatcolor.green:
    description: Allows the player to use green chat color.
    default: op
  easycommands.chatcolor.blue:
    description: Allows the player to use blue chat color.
    default: op
  easycommands.chatcolor.yellow:
    description: Allows the player to use yellow chat color.
    default: op
  easycommands.chatcolor.aqua:
    description: Allows the player to use aqua chat color.
    default: op
  easycommands.chatcolor.gold:
    description: Allows the player to use gold chat color.
    default: op
  easycommands.chatcolor.italic:
    description: Allows the player to use italic chat option.
    default: op
  easycommands.chatcolor.bold:
    description: Allows the player to use bold chat option.
    default: op
  easycommands.chatcolor.underline:
    description: Allows the player to use underline chat option.
    default: op
  easycommands.chatcolor.light_purple:
    description: Allows the player to use light purple chat color.
    default: op
  easycommands.chatcolor.dark_gray:
    description: Allows the player to use dark gray chat color.
    default: op
  easycommands.chatcolor.white:
    description: Allows the player to use white chat color.
    default: op
  easycommands.pickup.autopickup:
    description: permissions for autopickup.
    default: op
  easycommands.pickup.autosmelt:
    description: permissions for autosmelt.
    default: op
  easycommands.pickup.other:
    description: toggle other playes their pickups
    default: op
  easycommands.pickup.*:
    description: permissions for all pickup settings
    default: op
  easycommands.flight.others:
    description: toggle other people their flight
    default: op
  easycommands.gamemode.creative:
    description: creative gamemode
    default: op
  easycommands.gamemode.spectator:
    description: Spectator gamemode
  easycommands.gamemode.survival:
    description: Surival gamemode
    default: op
  easycommands.gamemode.adventure:
    description: Adventure gamemode
    default: op
  easycommands.reports.manage:
    description: Manage reports
    default: op
  easycommands.reports.getreports:
    description: View reports
    default: op
  easycommands.reports.reportnotify:
    description: information about reporting
    default: op
  easycommands.reports.bypasscooldown:
    description: Bypass the report cooldown
    default: op
  easycommands.staffhelp.bypasscooldown:
    description: bypass the help cooldown
    default: op
  easycommands.kill.players:
    description: kill players
    default: op
  easycommands.kill.all:
    description: kill everyone
    default: op
  easycommands.kill.mobs:
    description: kill mobs
    default: op
